BankAxept/bankaxept-epayment-development-kit

- openapi/integrator/token-requestor/client.yaml
- Adds response codes to the token requestor client API
- Adds messageId to the token update endpoint
> EBAX-1044: Improvements to token requestor client API

- java/base-client/src/main/java/no/bankaxept/epayment/client/base/BaseClient.java
- java/base-client/src/main/java/no/bankaxept/epayment/client/base/http/HttpClient.java
- java/client-test/src/test/java/no/bankaxept/epayment/test/client/merchant/MerchantClientTest.java
- java/merchant-client/src/main/java/no/bankaxept/epayment/client/merchant/MerchantClient.java
- java/merchant-client/src/main/java/no/bankaxept/epayment/client/merchant/SimulationCutOffRequest.java
- java/webflux-client/src/main/java/no/bankaxept/epayment/client/webflux/WebFluxClient.java
- openapi/integrator/components.yaml
- openapi/integrator/merchant/client.yaml
- openapi/integrator/merchant/server.yaml
Sorry for some whitespace changes here and there.. 
___________________________________________________
There's a need to include the merchantAggregatorId in the request now, to find the correct URL to send the callback to. Also added messageId to cutoff request as well.
> 822 merchant reconciliation

- java/client-test/pom.xml
- pom.xml
Merging to main so we can point to a proper commit..
> Update spring boot

- openapi/integrator/components.yaml
- openapi/integrator/wallet/client.yaml
- openapi/integrator/wallet/server.yaml
Added ~~authorizationURL~~ authenticationURL tokenId to the notification towards merchant we'll send after registering permissions for enrolment.
> BankID OIDC flow 

- openapi/integrator/merchant/partner.yaml
- openapi/integrator/token-requestor/partner.yaml
- openapi/integrator/wallet/bankaxept.yaml
- openapi/integrator/wallet/partner.yaml
Main PR: https://github.com/techcloud0/bankaxept-epayment-platform/pull/1672
> OpenAPI spec changes to enable card enrolment 

- openapi/integrator/token-requestor/bankaxept.yaml
For the record, I don't really like how the response is provided,  but it serves the purpose.
> Add a new eligible banks operation

- java/client-test/src/test/java/no/bankaxept/epayment/client/test/merchant/MerchantClientIT.java
- java/client-test/src/test/java/no/bankaxept/epayment/client/test/tokenrequestor/TokenRequestorClientIT.java
- java/client-test/src/test/java/no/bankaxept/epayment/client/test/wallet/WalletClientIT.java
- openapi/access-token/bankaxept.yaml
- openapi/integrator/merchant/bankaxept.yaml
- openapi/integrator/token-requestor/bankaxept.yaml
- openapi/integrator/wallet/bankaxept.yaml
Related to/goes together with: https://github.com/techcloud0/bankaxept-epayment-platform/pull/1986
> New domain names are not supported by devkit

- docs/authentication_interoperability.md
- docs/enrolment_and_payment.md
- docs/getting_started.md
Changed swagger pathing to align with Github Pages
> chore: changed swagger pathing to align with Github Pages

- openapi/integrator/token-requestor/partner.yaml
New enrolment status is added to tokent-requestor API.
> feat: add new enrolment status to api specification

- openapi/integrator/token-requestor/partner.yaml
New enrolment status is added to tokent-requestor API.
[To addition to](https://github.com/BankAxept/bankaxept-epayment-development-kit/pull/165).
> fix: updates to enrolment statuses in api specification

- README.md
- docs/authentication_interoperability.md
- docs/enrolment_and_payment.md
- docs/getting_started.md
- mkdocs.yml
Guidelines for refund/capture etc.
> chore: Guidelines for operations after payment request.

- docs/authentication_interoperability.md
Adding a script for educational purposes. This script demonstrates how to create a digest using a JSON object.
> chore: Add bash script for digest creation as example

- README.md
- docs/README.md
- docs/api_policy.md
- docs/assets/javascripts/mermaid-init.js
- docs/authentication_interoperability.md
- docs/getting_started.md
- mkdocs.yml
Created an overview on handling timeouts.
Added a sync between Mkdocs and Mermaid themes.
> Chore: Timeout guidelines and Mkdocs/Mermaid theme

- openapi/integrator/token-requestor/partner.yaml
Create 2 layers of enrollment result reporting.
Enrolmentstatus becomes the main status indicator.
Errocode becomes an in depth additional information field. Giving more exact reason for enrolment failures.
> feat: Remove enrolment statuses and add errocodes by aligning to new structure

- openapi/integrator/token-requestor/partner.yaml
This adds ErrorCode as a property, ensuring proper OpenAPI generation.
> fix: Add ErrorCode as a property to CardEnrolmentResponse.

- docs/enrolment_and_payment.md
- docs/getting_started.md
This describes how to do amount based test scenarios and what http protocol must be supported.
> Add amount based scenarios and http protocol

- docs/enrolment_and_payment.md
- docs/getting_started.md
Make corrections on format and specify test context for amounts on payments.
> Make corrections on format and specify test context

- docs/enrolment_and_payment.md
This PR creates a reference for discussions when we are talking about corner cases impacting transaction operations.
> Add Possible Failure Reasons for Capture and Refund

- openapi/integrator/token-requestor/bankaxept.yaml
Improved descriptions of response codes for the card eligibility endpoint
> chore: Improve eligible card response code descriptions

- openapi/integrator/merchant/bankaxept.yaml
Update merchantLocation of PaymentRequest to make address optional instead of required
> Update merchantLocation of PaymentRequest to make address optional instead of required
